services:
  backend:
    image: ghcr.io/thegamerfarmer/rekor/backend:latest
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://db:27017
      - MONGODB_DB=${DB_NAME}
      - MONGODB_USER=${DB_USER}
      - MONGODB_PASSWORD=${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

  frontend-web:
    image: ghcr.io/thegamerfarmer/rekor/frontend-web:latest
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy

  db:
    image: mongo:8.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
