name: Main docker construct

on:
  workflow_run:
    workflows: ["Backend CI", "Frontend Web CI"]
    types: [completed]
    branches: [main]

jobs:
  publish:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Main docker construct
        run: docker compose -f docker-compose.prod.yml publish -y ghcr.io/thegamerfarmer/rekor:latest
